default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  encoding: unicode
  database: jonathanschack
  pool: 5
  username: jonathanschack
 
  timeout: 5000



production:
  <<: *default
  database: jonathanschack
  username: jonathanschack
 


  test:
  adapter: postgresql
  encoding: unicode
  database: jonathanschack
  pool: 5
  username: jonathanschack
  timeout: 5000